spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:liquibase/changelog.yaml
